version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo 'install'
      - docker -version
  pre_build:
    commands:
      - echo 'pre build'
      - pip install -r requirements.txt

  build:
    commands:
      - echo build
      - docker build -t app .
artifacts:
  files:
    - 'FLASK APP'

