version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo 'install'
      - docker --version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t flask:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker tag flask:latest 985920242639.dkr.ecr.eu-west-2.amazonaws.com/flask:latest
      - docker push 985920242639.dkr.ecr.eu-west-2.amazonaws.com/flask:latest
