version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo 'install'
      - docker --version
  pre_build:
    commands:
      - echo 'pre build'
      - pip install -r requirements.txt

  build:
    commands:
      - echo build
      - docker build -t app .

